%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/tobias/Documents/Bachelorarbeit/Data sets/Final Data/Combined Data.xlsx
%    Worksheet: Final Data Sets
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/12/15 15:24:38

%% Import the data
[~, ~, raw] = xlsread('/Users/tobias/Documents/Bachelorarbeit/Data sets/Final Data/Combined Data.xlsx','Final Data Sets');
raw = raw(4:192,41:71);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
USNGDP_1 = data(:,1);
USNGDP_2 = data(:,2);
USNGDP_3 = data(:,3);
USNGDP_4 = data(:,4);
USNGDP_5 = data(:,5);

USCPROF_1 = data(:,7);
USCPROF_2 = data(:,8);
USCPROF_3 = data(:,9);
USCPROF_4 = data(:,10);
USCPROF_5 = data(:,11);

USUNEMP_1 = data(:,13);
USUNEMP_2 = data(:,14);
USUNEMP_3 = data(:,15);
USUNEMP_4 = data(:,16);
USUNEMP_5 = data(:,17);

USINDPROD_1 = data(:,19);
USINDPROD_2 = data(:,20);
USINDPROD_3 = data(:,21);
USINDPROD_4 = data(:,22);
USINDPROD_5 = data(:,23);

USHOUSING_1 = data(:,25);
USHOUSING_2 = data(:,26);
USHOUSING_3 = data(:,27);
USHOUSING_4 = data(:,28);
USHOUSING_5 = data(:,29);

%% Clear temporary variables
clearvars data raw R;