%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/tobias/Documents/Bachelorarbeit/Data sets/Final Data/Combined Data.xlsx
%    Worksheet: WP sMAPE Preprocessed
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/01/30 11:08:58

%% Import the data
[~, ~, raw] = xlsread('/Users/tobias/Documents/Bachelorarbeit/Data sets/Final Data/Combined Data.xlsx','WP sMAPE Preprocessed');
raw = raw(12:1471,[1:9,12:20]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Tennet2015_16_Act = data(:,1);
Tennet2015_21_Act = data(:,2);
Tennet2015_31_Act = data(:,3);
Tennet2015_39_Act = data(:,4);

Tennet2015_16_For = data(:,6);
Tennet2015_21_For = data(:,7);
Tennet2015_31_For = data(:,8);
Tennet2015_39_For = data(:,9);

Hertz2015_15_Act = data(:,10);
Hertz2015_20_Act = data(:,11);
Hertz2015_30_Act = data(:,12);
Hertz2015_38_Act = data(:,13);

Hertz2015_15_For = data(:,15);
Hertz2015_20_For = data(:,16);
Hertz2015_30_For = data(:,17);
Hertz2015_38_For = data(:,18);




%% Clear temporary variables
clearvars data raw R;