%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/tobias/Documents/Bachelorarbeit/Data sets/Final Data/Combined Data.xlsx
%    Worksheet: WP Persistence
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/03/01 13:19:38

%% Import the data
[~, ~, raw] = xlsread('/Users/tobias/Documents/Bachelorarbeit/Data sets/Final Data/Combined Data.xlsx','WP Persistence');
raw = raw(48:35047,[6,8:14]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Pactual = data(:,1);
P15 = data(:,2);
P30 = data(:,3);
P45 = data(:,4);
P1 = data(:,5);
P2 = data(:,6);
P5 = data(:,7);
P10 = data(:,8);

%% Clear temporary variables
clearvars data raw R;